
name: projectlist

networks:
  internalnet:

services:

  # database
  db:
    restart: unless-stopped
    container_name: db
    image: postgres:alpine
    environment:
      TZ: Europe/Bratislava
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-unsafepasswordifnotspecified}
    volumes: 
      - dbdata:/var/lib/postgresql/data
    networks: 
      - internalnet
    ports: 
    # publish to different than standard port, so as not to interfere with
    # existing running instances
    # Publis, mainly for debug, therefore only locally
      - published: 5433
        target: 5432
        host_ip: 127.0.0.1
    # ------------
    # tty: true
    # command: echo I am db image
    # build:
      # context: db
      # dockerfile: Dockerfile

  # backend
  be:
    restart: unless-stopped
    container_name: be
    # image: eclipse-temurin:21.0.4_7-jre-ubi9-minimal
    # image: eclipse-temurin:21.0.4_7-jdk-ubi9-minimal
    # image: alpine:3.20.3
    
    # name that does not exist on docker hub or elsewhere,
    # therefore build will be forced
    image: local/be
    build:
      context: be
    depends_on:
      - db
    networks: 
      - internalnet
    ports:
      - published: 8080
        target: 8080
        host_ip: 127.0.0.1
    # -----------
    tty: true

  # frontend
  fe:
    restart: unless-stopped
    container_name: fe
    image: debian:latest
    # -----------
    tty: true
    networks: 
      - internalnet
    environment:
      TZ: Europe/Bratislava

volumes:
  dbdata: