
name: projectlist

networks:
  internalnet:

services:

  # database
  db:
    restart: unless-stopped
    container_name: db
    image: postgres:alpine
    environment:
      TZ: Europe/Bratislava
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-unsafepasswordifnotspecified}
    volumes: 
      - dbdata:/pgdata
    networks: 
      - internalnet
    ports: 
    # publish to different than standard port, so as not to interfere with
    # existing running instances
    # Publis, mainly for debug, therefore only locally
      - published: 5433
        target: 5432
        host_ip: 127.0.0.1
    # ------------
    # tty: true
    # command: echo I am db image
    # build:
      # context: db
      # dockerfile: Dockerfile

  # backend
  be:
    restart: unless-stopped
    container_name: be
    image: ubuntu:latest
    depends_on:
      - db
    networks: 
      - internalnet
    # -----------
    tty: true

  # frontend
  fe:
    restart: unless-stopped
    container_name: fe
    image: ubuntu:latest
    # -----------
    tty: true

volumes:
  dbdata: